{{ config(
      alias='CUSTOMER_REF'
    , materialized='table')
}}


WITH CUSTOMER AS (
SELECT  C_CUSTKEY AS CUSTOMER_KEY
      , 'F' AS CUSTOMER_TYPE
      , MOD(ROW_NUMBER() OVER (PARTITION BY '' ORDER BY C_CUSTKEY) , 5 ) AS CUSTOMER_SEQ
      , CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS DT_LOAD         
FROM {{ source('SF_SAMPLE', 'CUSTOMER') }} 
)
SELECT
      CUSTOMER.CUSTOMER_KEY
    , CUSTOMER.CUSTOMER_TYPE
    , CUSTOMER.CUSTOMER_SEQ
    , CUSTOMER.DT_LOAD
FROM CUSTOMER CUSTOMER
/*
      ESTA ESTRUCTURA DEBERIA DE FUNCIONAR PARA RELACIONAR MODELOS DE DIFERENTES PROYECTOS

LEFT JOIN ref('demo_dv','HUB_CUSTOMER') HUB
    ON HUB.CUSTOMER_KEY = CUSTOMER.CUSTOMER_KEY
    
*/
