SELECT 
    MODEL_NAME
    , ENVIRONMENT
    , COUNT(*) AS NUMBER_OF_ERRORED_EXECUTIONS 
FROM 
    {{ source('CUSTOM_LOG','EXECUTION_LOG_TABLE') }}
WHERE STATUS = 'ERROR'
GROUP BY
      MODEL_NAME
    , ENVIRONMENT
