USE ROLE ACCOUNTADMIN;

DROP WAREHOUSE IF EXISTS EDW_WH;

USE ROLE SECURITYADMIN;

DROP ROLE IF EXISTS SDGADMIN;
USE ROLE SYSADMIN;

CREATE OR REPLACE DATABASE EDW_DV_DEMO COMMENT = 'Demo database to be used by SDG';
CREATE OR REPLACE DATABASE EDW_DV COMMENT = 'Demo database to be used by SDG';

USE EDW_DV_DEMO;

USE ROLE SECURITYADMIN;

CREATE OR REPLACE ROLE SDGADMIN COMMENT = 'EDW_DV_DEMO resources admin';
GRANT USAGE ON DATABASE EDW_DV_DEMO TO ROLE SDGADMIN;
GRANT USAGE ON DATABASE EDW_DV TO ROLE SDGADMIN;

USE ROLE ACCOUNTADMIN;
CREATE DATABASE IF NOT EXISTS SNOWFLAKE_SAMPLE_DATA FROM share SFC_SAMPLES.SAMPLE_DATA; 

GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE_SAMPLE_DATA TO ROLE SDGADMIN;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE_SAMPLE_DATA TO SYSADMIN;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE_SAMPLE_DATA to role PUBLIC;

USE ROLE SECURITYADMIN;
GRANT CREATE SCHEMA ON DATABASE EDW_DV_DEMO TO ROLE SDGADMIN;
GRANT CREATE SCHEMA ON DATABASE EDW_DV TO ROLE SDGADMIN;

GRANT ROLE SDGADMIN TO ROLE SYSADMIN;

USE ROLE ACCOUNTADMIN;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE SDGADMIN;
GRANT EXECUTE MANAGED TASK ON ACCOUNT TO ROLE SDGADMIN;

CREATE OR REPLACE USER SDGUSER
    PASSWORD = "SDGUSER"
    DEFAULT_ROLE = SDGADMIN;   
   
GRANT ROLE SDGADMIN TO USER SDGUSER;   

ALTER ACCOUNT SET TIMEZONE = 'Europe/Madrid';
   

GRANT CREATE WAREHOUSE ON ACCOUNT TO SDGADMIN;


ALTER ACCOUNT SET DATE_OUTPUT_FORMAT = 'DD/MM/YYYY';

ALTER ACCOUNT SET WEEK_START = 1;

USE ROLE SDGADMIN;

CREATE WAREHOUSE EDW_WH WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE;