/*
 *	START	INIT DATABASE FOR PROD ENVIRONMENT 
 * */

USE ROLE SDGADMIN;
USE DATABASE EDW_DV;
USE WAREHOUSE EDW_WH;

--SCHEMAS DATA OPS VAULT
CREATE OR REPLACE SCHEMA RAW_DATAVAULT;
CREATE OR REPLACE SCHEMA BUSINESS_VAULT;
CREATE OR REPLACE SCHEMA INFORMATION_MART;
CREATE OR REPLACE SCHEMA LANDING;
CREATE OR REPLACE SCHEMA REF_DATA;
CREATE OR REPLACE SCHEMA SEMANTIC_MODEL;
CREATE OR REPLACE SCHEMA OBSERVABILITY;


CREATE OR REPLACE TABLE LANDING.CUSTOMER AS SELECT *, CURRENT_TIMESTAMP AS DT_LOAD FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.CUSTOMER; 
CREATE OR REPLACE TABLE LANDING.LINEITEM AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM;
CREATE OR REPLACE TABLE LANDING.NATION   AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.NATION;
CREATE OR REPLACE TABLE LANDING.ORDERS   AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.ORDERS;
CREATE OR REPLACE TABLE LANDING.PART     AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PART;
CREATE OR REPLACE TABLE LANDING.PARTSUPP AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PARTSUPP;
CREATE OR REPLACE TABLE LANDING.SUPPLIER AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.SUPPLIER;
CREATE OR REPLACE TABLE LANDING.REGION   AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.REGION;



/*
 *	END	INIT DATABASE FOR DEMO 
 * */


create or replace TABLE EDW_DV.RAW_DATAVAULT.HUB_CUSTOMER (
	HUB_ID_CUSTOMER VARCHAR,
	CUSTOMER_KEY NUMBER(38,0),
	TENANT VARCHAR,
	DT_LOAD TIMESTAMP_NTZ,
	RECORD_SOURCE VARCHAR
);

create or replace TABLE EDW_DV.RAW_DATAVAULT.HUB_ORDERS (
	HUB_ID_ORDERS VARCHAR,
	ORDER_KEY NUMBER(38,0),
	TENANT VARCHAR,
	DT_LOAD TIMESTAMP_NTZ,
	RECORD_SOURCE VARCHAR
);


create or replace TABLE EDW_DV.RAW_DATAVAULT.HUB_SUPPLIER (
	HUB_ID_SUPPLIER VARCHAR,
	SUPPLIER_KEY NUMBER(38,0),
	TENANT VARCHAR,
	DT_LOAD TIMESTAMP_NTZ,
	RECORD_SOURCE VARCHAR
);

create or replace TABLE EDW_DV.RAW_DATAVAULT.HUB_PART (
	HUB_ID_PART VARCHAR,
	PART_KEY NUMBER(38,0),
	TENANT VARCHAR,
	DT_LOAD TIMESTAMP_NTZ,
	RECORD_SOURCE VARCHAR
);
create or replace TABLE EDW_DV.RAW_DATAVAULT.HUB_REGION (
	HUB_ID_REGION VARCHAR,
	REGION_KEY NUMBER(38,0),
	TENANT VARCHAR,
	DT_LOAD TIMESTAMP_NTZ,
	RECORD_SOURCE VARCHAR
);
create or replace TABLE EDW_DV.RAW_DATAVAULT.HUB_NATION (
	HUB_ID_NATION VARCHAR,
	NATION_KEY NUMBER(38,0),
	TENANT VARCHAR,
	DT_LOAD TIMESTAMP_NTZ,
	RECORD_SOURCE VARCHAR
);

/*
 * 			END HUBS
 * */



create or replace TABLE EDW_DV.RAW_DATAVAULT.LNK_ORDERS_CUSTOMER (
	LINK_ID_ORDERS_CUSTOMER VARCHAR,
	HUB_ID_ORDERS VARCHAR,
	HUB_ID_CUSTOMER VARCHAR,	
	ORDERS_KEY NUMBER(38,0),
	CUSTOMER_KEY NUMBER(38,0),
	TENANT VARCHAR,
	DT_LOAD TIMESTAMP_NTZ,
	RECORD_SOURCE VARCHAR
);


create or replace TABLE EDW_DV.RAW_DATAVAULT.LNK_CUSTOMER_NATION (
	LINK_ID_CUSTOMER_NATION VARCHAR,
	HUB_ID_CUSTOMER VARCHAR,
	HUB_ID_NATION VARCHAR,	
	CUSTOMER_KEY NUMBER(38,0),
	NATION_KEY NUMBER(38,0),
	TENANT VARCHAR,
	DT_LOAD TIMESTAMP_NTZ,
	RECORD_SOURCE VARCHAR
);




create or replace TABLE EDW_DV.RAW_DATAVAULT.LNK_NATION_REGION (
	LINK_ID_NATION_REGION VARCHAR,
	HUB_ID_NATION VARCHAR,
	HUB_ID_REGION VARCHAR,	
	NATION_KEY NUMBER(38,0),
	REGION_KEY NUMBER(38,0),
	TENANT VARCHAR,
	DT_LOAD TIMESTAMP_NTZ,
	RECORD_SOURCE VARCHAR
);


create or replace TABLE EDW_DV.RAW_DATAVAULT.LNK_SUPPLIER_NATION (
	LINK_ID_SUPPLIER_NATION VARCHAR,
	HUB_ID_SUPPLIER VARCHAR,
	HUB_ID_NATION VARCHAR,	
	SUPPLIER_KEY NUMBER(38,0),
	NATION_KEY NUMBER(38,0),
	TENANT VARCHAR,
	DT_LOAD TIMESTAMP_NTZ,
	RECORD_SOURCE VARCHAR
);




create or replace TABLE EDW_DV.RAW_DATAVAULT.LNK_LINEITEM_ORDERS_PART_SUPPLIER (
	LINK_ID_LINEITEM_OPS VARCHAR,
	HUB_ID_ORDERS VARCHAR,
	HUB_ID_PART VARCHAR,	
	HUB_ID_SUPPLIER VARCHAR,
	ORDERS_KEY NUMBER(38,0),
	PART_KEY NUMBER(38,0),
	SUPPLIER_KEY NUMBER(38,0),
	TENANT VARCHAR,
	DT_LOAD TIMESTAMP_NTZ,
	RECORD_SOURCE VARCHAR
);

create or replace TABLE EDW_DV.RAW_DATAVAULT.LNK_PART_SUPPLIER (
	LINK_ID_PART_SUPPLIER VARCHAR,
	HUB_ID_PART VARCHAR,	
	HUB_ID_SUPPLIER VARCHAR,
	PART_KEY NUMBER(38,0),
	SUPPLIER_KEY NUMBER(38,0),
	TENANT VARCHAR,
	DT_LOAD TIMESTAMP_NTZ,
	RECORD_SOURCE VARCHAR
);




/*
 * 			END LINKS
 * */

create or replace TABLE EDW_DV.RAW_DATAVAULT.SAT_CUSTOMER_CONTACT_v1 (
	HUB_ID_CUSTOMER VARCHAR,
	TENANT VARCHAR,
	CUSTOMER_NAME VARCHAR,
	CUSTOMER_ADDRESS VARCHAR,
	CUSTOMER_PHONE VARCHAR,
	DT_LOAD TIMESTAMP_NTZ,
	HASH_DIFF VARCHAR,
	RECORD_SOURCE VARCHAR
);

create or replace TABLE EDW_DV.RAW_DATAVAULT.SAT_CUSTOMER_CONTACT_v2 (
	HUB_ID_CUSTOMER VARCHAR,
	TENANT VARCHAR,
	CUSTOMER_NAME VARCHAR,
	CUSTOMER_ADDRESS VARCHAR,
	CUSTOMER_PHONE VARCHAR,
	DT_LOAD TIMESTAMP_NTZ,
	DT_LOAD_BATCH TIMESTAMP_NTZ,
	HASH_DIFF VARCHAR,
	RECORD_SOURCE VARCHAR
);

create or replace TABLE EDW_DV.RAW_DATAVAULT.SAT_CUSTOMER_METRICS (
	HUB_ID_CUSTOMER VARCHAR,
	TENANT VARCHAR,
	ACCOUNT_BALANCE NUMBER(12,2),
	SEGMENT VARCHAR,
	DT_LOAD TIMESTAMP_NTZ,
	HASH_DIFF VARCHAR,
	RECORD_SOURCE VARCHAR
);


create or replace TABLE EDW_DV.RAW_DATAVAULT.SAT_NATION_DETAIL (
	HUB_ID_NATION VARCHAR,
	TENANT VARCHAR,
	NATION VARCHAR,
	COMMENT VARCHAR,
	DT_LOAD TIMESTAMP_NTZ,
	HASH_DIFF VARCHAR,
	RECORD_SOURCE VARCHAR
);

create or replace TABLE EDW_DV.RAW_DATAVAULT.SAT_ORDERS_DETAIL (
	HUB_ID_ORDERS VARCHAR,
	TENANT VARCHAR,
	CLERK  VARCHAR,
	ORDER_PRIORITY VARCHAR,
	SHIP_PRIORITY NUMBER(38,0),
	COMMENT VARCHAR,
	DT_LOAD TIMESTAMP_NTZ,
	HASH_DIFF VARCHAR,
	RECORD_SOURCE VARCHAR
);

create or replace TABLE EDW_DV.RAW_DATAVAULT.SAT_ORDERS_MAIN (
	HUB_ID_ORDERS VARCHAR,
	TENANT VARCHAR,
	STATUS  VARCHAR,
	ORDER_DATE DATE,
	TOTAL_PRICE NUMBER(12,2),
	DT_LOAD TIMESTAMP_NTZ,
	HASH_DIFF VARCHAR,
	RECORD_SOURCE VARCHAR
);


create or replace TABLE EDW_DV.RAW_DATAVAULT.SAT_PART_STATIC (
	HUB_ID_PART VARCHAR,
	TENANT VARCHAR,
	NAME  VARCHAR,
	MANUFACTURER VARCHAR,
	BRAND VARCHAR,
	TYPE VARCHAR,
	COMMENT VARCHAR,	
	DT_LOAD TIMESTAMP_NTZ,
	HASH_DIFF VARCHAR,
	RECORD_SOURCE VARCHAR
);

create or replace TABLE EDW_DV.RAW_DATAVAULT.SAT_PART_MAIN (
	HUB_ID_PART VARCHAR,
	TENANT VARCHAR,
	SIZE  NUMBER(38,0),
	CONTAINER VARCHAR,
	RETAIL_PRICE NUMBER(12,2),
	DT_LOAD TIMESTAMP_NTZ,
	HASH_DIFF VARCHAR,
	RECORD_SOURCE VARCHAR
);

create or replace TABLE EDW_DV.RAW_DATAVAULT.SAT_REGION_DETAIL (
	HUB_ID_REGION VARCHAR,
	TENANT VARCHAR,
	REGION VARCHAR,
	COMMENT VARCHAR,
	DT_LOAD TIMESTAMP_NTZ,
	HASH_DIFF VARCHAR,
	RECORD_SOURCE VARCHAR
);


create or replace TABLE EDW_DV.RAW_DATAVAULT.SAT_SUPPLIER_STATIC (
	HUB_ID_SUPPLIER VARCHAR,
	TENANT VARCHAR,
	NAME VARCHAR,
	ADDRESS VARCHAR,
	PHONE VARCHAR,
	DT_LOAD TIMESTAMP_NTZ,
	HASH_DIFF VARCHAR,
	RECORD_SOURCE VARCHAR
);

create or replace TABLE EDW_DV.RAW_DATAVAULT.SAT_SUPPLIER_DETAIL (
	HUB_ID_SUPPLIER VARCHAR,
	TENANT VARCHAR,
	ACCOUNT_BALANCE NUMBER(12,2),
	COMMENT VARCHAR,
	DT_LOAD TIMESTAMP_NTZ,
	HASH_DIFF VARCHAR,
	RECORD_SOURCE VARCHAR
);


create or replace TABLE EDW_DV.RAW_DATAVAULT.SATL_LINEITEM_OPS_DETAIL (
	LINK_ID_LINEITEM_OPS VARCHAR,
	TENANT VARCHAR,
	LINE_NUMBER NUMBER(38,0),
	LINE_STATUS VARCHAR,
	QUANTITY NUMBER(12,2),
	EXTENDED_PRICE NUMBER(12,2),
	DISCOUNT NUMBER(12,2),
	TAX NUMBER(12,2),
	RETURN_FLAG VARCHAR,
	DT_LOAD TIMESTAMP_NTZ,
	HASH_DIFF VARCHAR,
	RECORD_SOURCE VARCHAR
);

create or replace TABLE EDW_DV.RAW_DATAVAULT.SATL_LINEITEM_OPS_DATES (
	LINK_ID_LINEITEM_OPS VARCHAR,
	TENANT VARCHAR,
	SHIP_DATE DATE,
	COMMIT_DATE DATE,
	RECEIPT_DATE DATE,
	SHIP_INSTRUCTIONS VARCHAR,
	SHIP_MODE VARCHAR,
	COMMENT VARCHAR,
	DT_LOAD TIMESTAMP_NTZ,
	HASH_DIFF VARCHAR,
	RECORD_SOURCE VARCHAR
);


/*
 * 			END SATS & SATLS
 * */


/*
 * 			LOG TABLE
 * */


create or replace TABLE EDW_DV.RAW_DATAVAULT.EXECUTION_LOG_TABLE (
	RUN_ID  VARCHAR(16777216),
	RUN_STARTED_AT  TIMESTAMP_NTZ(9),
	DBT_VERSION VARCHAR(16777216),
	PROJECT_NAME VARCHAR(16777216),
	MODEL_NAME VARCHAR(16777216),
	STATUS VARCHAR(16777216),
	ERROR_MESSAGE VARCHAR(16777216),
	ENVIRONMENT VARCHAR(16777216),
	DATABASE VARCHAR(16777216),
	DT_LOAD TIMESTAMP_NTZ(9)
);