{{ config(
      alias='HUB_CUSTOMER'
    , materialized='incremental')
}}


WITH CUSTOMER AS (
SELECT 
        MD5(C_CUSTKEY) AS HUB_ID_CUSTOMER
      , C_CUSTKEY AS CUSTOMER_KEY
      , '{{ var('cod_tenant') }}' AS TENANT
      , CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS DT_LOAD   
      , '{{ source('SF_SAMPLE', 'CUSTOMER') }}' AS RECORD_SOURCE
FROM {{ source('SF_SAMPLE', 'CUSTOMER') }} 
)
SELECT         
        CUSTOMER.HUB_ID_CUSTOMER
      , CUSTOMER.CUSTOMER_KEY
      , CUSTOMER.TENANT
      , CUSTOMER.DT_LOAD
      , CUSTOMER.RECORD_SOURCE
FROM CUSTOMER CUSTOMER
LEFT JOIN {{ this }} HUB
	ON HUB.HUB_ID_CUSTOMER =  CUSTOMER.HUB_ID_CUSTOMER
WHERE HUB.HUB_ID_CUSTOMER IS NULL