{{ config(
      alias='LNK_SUPPLIER_NATION'
    , materialized='incremental')
}}


WITH SUP_NAT AS (
SELECT 
        MD5(S_SUPPKEY||S_NATIONKEY) LINK_ID_SUPPLIER_NATION
      , MD5(S_SUPPKEY)  AS HUB_ID_SUPPLIER
      , MD5(S_NATIONKEY) AS HUB_ID_NATION
      , S_SUPPKEY AS SUPPLIER_KEY
      , S_NATIONKEY  AS NATION_KEY
      , '{{ var('cod_tenant') }}' AS TENANT
      , CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS DT_LOAD   
      , '{{ source('SF_SAMPLE', 'SUPPLIER') }}' AS RECORD_SOURCE
FROM {{ source('SF_SAMPLE', 'SUPPLIER') }} 
)
SELECT         
        SUP_NAT.LINK_ID_SUPPLIER_NATION
      , SUP_NAT.HUB_ID_SUPPLIER
      , SUP_NAT.HUB_ID_NATION
      , SUP_NAT.SUPPLIER_KEY
      , SUP_NAT.NATION_KEY
      , SUP_NAT.TENANT
      , SUP_NAT.DT_LOAD
      , SUP_NAT.RECORD_SOURCE
FROM SUP_NAT SUP_NAT
LEFT JOIN {{ this }} LINK
	ON LINK.LINK_ID_SUPPLIER_NATION =  SUP_NAT.LINK_ID_SUPPLIER_NATION
WHERE LINK.LINK_ID_SUPPLIER_NATION IS NULL