{{ config(
      alias='LNK_NATION_REGION'
    , materialized='incremental')
}}


WITH NAT_REG AS (
SELECT 
        MD5(N_NATIONKEY||N_REGIONKEY) LINK_ID_NATION_REGION
      , MD5(N_NATIONKEY)  AS HUB_ID_NATION
      , MD5(N_REGIONKEY) AS HUB_ID_REGION
      , N_NATIONKEY AS NATION_KEY
      , N_REGIONKEY  AS REGION_KEY
      , '{{ var('cod_tenant') }}' AS TENANT
      , CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS DT_LOAD   
      , '{{ source('SF_SAMPLE', 'NATION') }}' AS RECORD_SOURCE
FROM {{ source('SF_SAMPLE', 'NATION') }} 
)
SELECT         
        NAT_REG.LINK_ID_NATION_REGION
      , NAT_REG.HUB_ID_NATION
      , NAT_REG.HUB_ID_REGION
      , NAT_REG.NATION_KEY
      , NAT_REG.REGION_KEY
      , NAT_REG.TENANT
      , NAT_REG.DT_LOAD
      , NAT_REG.RECORD_SOURCE
FROM NAT_REG NAT_REG
LEFT JOIN {{ this }} LINK
	ON LINK.LINK_ID_NATION_REGION =  NAT_REG.LINK_ID_NATION_REGION
WHERE LINK.LINK_ID_NATION_REGION IS NULL