{{ config(
      alias='LNK_PART_SUPPLIER'
    , materialized='incremental')
}}


WITH PAR_SUP AS (
SELECT 
        MD5(PS_PARTKEY||PS_SUPPKEY) LINK_ID_PART_SUPPLIER
      , MD5(PS_PARTKEY)  AS HUB_ID_PART
      , MD5(PS_SUPPKEY) AS HUB_ID_SUPPLIER
      , PS_PARTKEY AS PART_KEY
      , PS_SUPPKEY  AS SUPPLIER_KEY
      , '{{ var('cod_tenant') }}' AS TENANT
      , CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS DT_LOAD   
      , '{{ source('SF_SAMPLE', 'PARTSUPP') }}' AS RECORD_SOURCE
FROM {{ source('SF_SAMPLE', 'PARTSUPP') }} 
)
SELECT         
        PAR_SUP.LINK_ID_PART_SUPPLIER
      , PAR_SUP.HUB_ID_PART
      , PAR_SUP.HUB_ID_SUPPLIER
      , PAR_SUP.PART_KEY
      , PAR_SUP.SUPPLIER_KEY
      , PAR_SUP.TENANT
      , PAR_SUP.DT_LOAD
      , PAR_SUP.RECORD_SOURCE
FROM PAR_SUP PAR_SUP
LEFT JOIN {{ this }} LINK
	ON LINK.LINK_ID_PART_SUPPLIER =  PAR_SUP.LINK_ID_PART_SUPPLIER
WHERE LINK.LINK_ID_PART_SUPPLIER IS NULL