{{ config(
      alias='LNK_ORDERS_CUSTOMER'
    , materialized='incremental')
}}


WITH ORD_CUST AS (
SELECT 
        MD5(O_ORDERKEY||O_CUSTKEY) LINK_ID_ORDERS_CUSTOMER
      , MD5(O_ORDERKEY) AS HUB_ID_ORDERS
      , MD5(O_CUSTKEY)  AS HUB_ID_CUSTOMER
      , O_ORDERKEY AS ORDERS_KEY
      , O_CUSTKEY  AS CUSTOMER_KEY
      , '{{ var('cod_tenant') }}' AS TENANT
      , CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS DT_LOAD   
      , '{{ source('SF_SAMPLE', 'ORDERS') }}' AS RECORD_SOURCE
FROM {{ source('SF_SAMPLE', 'ORDERS') }} 
)
SELECT         
        ORD_CUST.LINK_ID_ORDERS_CUSTOMER
      , ORD_CUST.HUB_ID_ORDERS
      , ORD_CUST.HUB_ID_CUSTOMER
      , ORD_CUST.ORDERS_KEY
      , ORD_CUST.CUSTOMER_KEY
      , ORD_CUST.TENANT
      , ORD_CUST.DT_LOAD
      , ORD_CUST.RECORD_SOURCE
FROM ORD_CUST ORD_CUST
LEFT JOIN {{ this }} LINK
	ON LINK.LINK_ID_ORDERS_CUSTOMER =  ORD_CUST.LINK_ID_ORDERS_CUSTOMER
WHERE LINK.LINK_ID_ORDERS_CUSTOMER IS NULL