{{ config(
      alias='LNK_LINEITEM_ORDERS_PART_SUPPLIER'
    , materialized='incremental')
}}


WITH OPS AS (
SELECT 
        MD5(L_ORDERKEY||L_PARTKEY||L_SUPPKEY) LINK_ID_LINEITEM_OPS
      , MD5(L_ORDERKEY) AS HUB_ID_ORDERS
      , MD5(L_PARTKEY) AS HUB_ID_PART
      , MD5(L_SUPPKEY) AS HUB_ID_SUPPLIER
      , L_ORDERKEY AS ORDERS_KEY
      , L_PARTKEY  AS PART_KEY
      , L_SUPPKEY  AS SUPPLIER_KEY
      , '{{ var('cod_tenant') }}' AS TENANT
      , CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS DT_LOAD   
      , '{{ source('SF_SAMPLE', 'LINEITEM') }}' AS RECORD_SOURCE
FROM {{ source('SF_SAMPLE', 'LINEITEM') }} 
)
SELECT         
        OPS.LINK_ID_LINEITEM_OPS
      , OPS.HUB_ID_ORDERS
      , OPS.HUB_ID_PART
      , OPS.HUB_ID_SUPPLIER
      , OPS.ORDERS_KEY
      , OPS.PART_KEY
      , OPS.SUPPLIER_KEY
      , OPS.TENANT
      , OPS.DT_LOAD
      , OPS.RECORD_SOURCE
FROM OPS OPS
LEFT JOIN {{ this }} LINK
	ON LINK.LINK_ID_LINEITEM_OPS =  OPS.LINK_ID_LINEITEM_OPS
WHERE LINK.LINK_ID_LINEITEM_OPS IS NULL