{{ config(
      alias='LNK_CUSTOMER_NATION'
    , materialized='incremental')
}}


WITH CUST_NAT AS (
SELECT 
        MD5(C_CUSTKEY||C_NATIONKEY) LINK_ID_CUSTOMER_NATION
      , MD5(C_CUSTKEY)  AS HUB_ID_CUSTOMER
      , MD5(C_NATIONKEY) AS HUB_ID_NATION
      , C_CUSTKEY AS CUSTOMER_KEY
      , C_NATIONKEY  AS NATION_KEY
      , '{{ var('cod_tenant') }}' AS TENANT
      , CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS DT_LOAD   
      , '{{ source('SF_SAMPLE', 'CUSTOMER') }}' AS RECORD_SOURCE
FROM {{ source('SF_SAMPLE', 'CUSTOMER') }} 
)
SELECT         
        CUST_NAT.LINK_ID_CUSTOMER_NATION
      , CUST_NAT.HUB_ID_CUSTOMER
      , CUST_NAT.HUB_ID_NATION
      , CUST_NAT.CUSTOMER_KEY
      , CUST_NAT.NATION_KEY
      , CUST_NAT.TENANT
      , CUST_NAT.DT_LOAD
      , CUST_NAT.RECORD_SOURCE
FROM CUST_NAT CUST_NAT
LEFT JOIN {{ this }} LINK
	ON LINK.LINK_ID_CUSTOMER_NATION =  CUST_NAT.LINK_ID_CUSTOMER_NATION
WHERE LINK.LINK_ID_CUSTOMER_NATION IS NULL