{{ config(
    materialized='incremental')
}}


WITH SAT_DATA AS (
SELECT  
      MD5(C_CUSTKEY) HUB_ID_CUSTOMER
      , '{{ var('cod_tenant') }}' AS TENANT
      , C_NAME AS CUSTOMER_NAME
      , C_ADDRESS AS CUSTOMER_ADDRESS
      , C_PHONE AS CUSTOMER_PHONE
      , CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS DT_LOAD
      , MD5(COALESCE(C_NAME,'#')
            ||COALESCE(C_ADDRESS,'#')
            ||COALESCE(C_NATIONKEY,0)
            ||COALESCE(C_PHONE,'#')
            ) HASH_DIFF
      , '{{ source('SF_SAMPLE', 'CUSTOMER') }}' AS RECORD_SOURCE
FROM {{ source('SF_SAMPLE', 'CUSTOMER') }} 
) 

SELECT 
      SAT_DATA.HUB_ID_CUSTOMER
      , SAT_DATA.TENANT
      , SAT_DATA.CUSTOMER_NAME
      , SAT_DATA.CUSTOMER_ADDRESS
      , SAT_DATA.CUSTOMER_PHONE
      , SAT_DATA.DT_LOAD
      , SAT_DATA.HASH_DIFF
      , SAT_DATA.RECORD_SOURCE
FROM SAT_DATA SAT_DATA
LEFT JOIN {{ this }} SAT
	ON SAT.HUB_ID_CUSTOMER =  SAT_DATA.HUB_ID_CUSTOMER
   AND SAT.HASH_DIFF = SAT_DATA.HASH_DIFF
WHERE SAT.HUB_ID_CUSTOMER IS NULL