{{ config(
    alias='SAT_CUSTOMER_METRICS'
    , materialized='incremental')
}}


WITH SAT_DATA AS (
SELECT  
      MD5(C_CUSTKEY) HUB_ID_CUSTOMER
      , '{{ var('cod_tenant') }}' AS TENANT
      , C_ACCTBAL AS ACCOUNT_BALANCE
      , C_MKTSEGMENT AS SEGMENT
      , CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS DT_LOAD
      , MD5(COALESCE(C_ACCTBAL,-1)
         ||COALESCE(C_MKTSEGMENT,'#')
        ) HASH_DIFF
      , '{{ source('SF_SAMPLE', 'CUSTOMER') }}' AS RECORD_SOURCE
FROM {{ source('SF_SAMPLE', 'CUSTOMER') }} 
)
SELECT 
      SAT_DATA.HUB_ID_CUSTOMER
      , SAT_DATA.TENANT
      , SAT_DATA.ACCOUNT_BALANCE
      , SAT_DATA.SEGMENT
      , SAT_DATA.DT_LOAD
      , SAT_DATA.HASH_DIFF
      , SAT_DATA.RECORD_SOURCE
FROM SAT_DATA SAT_DATA
LEFT JOIN {{ this }} SAT
	ON SAT.HUB_ID_CUSTOMER =  SAT_DATA.HUB_ID_CUSTOMER
   AND SAT.HASH_DIFF = SAT_DATA.HASH_DIFF
WHERE SAT.HUB_ID_CUSTOMER IS NULL