{{ config(
      alias='SAT_ORDERS_DETAIL'
    , materialized='incremental')
}}


WITH SAT_DATA AS (
SELECT  
      MD5(O_ORDERKEY) HUB_ID_ORDERS
      , '{{ var('cod_tenant') }}' AS TENANT      
      , O_CLERK AS CLERK
      , O_ORDERPRIORITY AS ORDER_PRIORITY
      , O_SHIPPRIORITY AS SHIP_PRIORITY
      , O_COMMENT AS COMMENT
      , CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS DT_LOAD            
      , MD5( COALESCE(O_CLERK,'#')
            ||COALESCE(O_ORDERPRIORITY,'#') 
            ||COALESCE(O_SHIPPRIORITY,-1) 
            ||COALESCE(O_COMMENT,'#') 
            ) HASH_DIFF
      , '{{ source('SF_SAMPLE', 'ORDERS') }}' AS RECORD_SOURCE
FROM {{ source('SF_SAMPLE', 'ORDERS') }} 
)

SELECT 
      SAT_DATA.HUB_ID_ORDERS
      , SAT_DATA.TENANT
      , SAT_DATA.CLERK
      , SAT_DATA.ORDER_PRIORITY
      , SAT_DATA.SHIP_PRIORITY
      , SAT_DATA.COMMENT
      , SAT_DATA.DT_LOAD
      , SAT_DATA.HASH_DIFF
      , SAT_DATA.RECORD_SOURCE
FROM SAT_DATA SAT_DATA
LEFT JOIN {{ this }} SAT
	ON SAT.HUB_ID_ORDERS =  SAT_DATA.HUB_ID_ORDERS
   AND SAT.HASH_DIFF = SAT_DATA.HASH_DIFF
WHERE SAT.HUB_ID_ORDERS IS NULL
