{{ config(
      alias='SAT_PART_MAIN'
    , materialized='incremental')
}}


WITH SAT_DATA AS (
SELECT  
      MD5(P_PARTKEY) HUB_ID_PART
      , '{{ var('cod_tenant') }}' AS TENANT      
      , P_SIZE AS SIZE
      , P_CONTAINER AS CONTAINER
      , P_RETAILPRICE AS RETAIL_PRICE
      , CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS DT_LOAD            
      , MD5( COALESCE(P_SIZE,-1)
            ||COALESCE(P_CONTAINER,'#') 
            ||COALESCE(P_RETAILPRICE,-1) 
            ) HASH_DIFF
      , '{{ source('SF_SAMPLE', 'PART') }}' AS RECORD_SOURCE
FROM {{ source('SF_SAMPLE', 'PART') }} 
)

SELECT 
      SAT_DATA.HUB_ID_PART
      , SAT_DATA.TENANT
      , SAT_DATA.SIZE
      , SAT_DATA.CONTAINER
      , SAT_DATA.RETAIL_PRICE
      , SAT_DATA.DT_LOAD
      , SAT_DATA.HASH_DIFF
      , SAT_DATA.RECORD_SOURCE
FROM SAT_DATA SAT_DATA
LEFT JOIN {{ this }} SAT
	ON SAT.HUB_ID_PART =  SAT_DATA.HUB_ID_PART
   AND SAT.HASH_DIFF = SAT_DATA.HASH_DIFF
WHERE SAT.HUB_ID_PART IS NULL

