{{ config(
      alias='SATL_LINEITEM_OPS_DETAIL'
    , materialized='incremental')
}}


WITH SAT_DATA AS (
SELECT  
        MD5(L_ORDERKEY||L_PARTKEY||L_SUPPKEY) LINK_ID_LINEITEM_OPS
      , '{{ var('cod_tenant') }}' AS TENANT      
      , L_LINENUMBER AS LINE_NUMBER
      , L_LINESTATUS AS LINE_STATUS
      , L_QUANTITY AS QUANTITY
      , L_EXTENDEDPRICE AS EXTENDED_PRICE
      , L_DISCOUNT AS DISCOUNT
      , L_TAX AS TAX
      , L_RETURNFLAG AS RETURN_FLAG
      , CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS DT_LOAD            
      , MD5( COALESCE(L_LINENUMBER,-1)
            ||COALESCE(L_LINESTATUS,'#') 
            ||COALESCE(L_QUANTITY,-1) 
            ||COALESCE(L_EXTENDEDPRICE,-1) 
            ||COALESCE(L_DISCOUNT,-1) 
            ||COALESCE(L_TAX,-1) 
            ||COALESCE(L_RETURNFLAG,'#') 
            ) HASH_DIFF
      , '{{ source('SF_SAMPLE', 'LINEITEM') }}' AS RECORD_SOURCE
FROM {{ source('SF_SAMPLE', 'LINEITEM') }} 
)

SELECT 
      SAT_DATA.LINK_ID_LINEITEM_OPS
      , SAT_DATA.TENANT
      , SAT_DATA.LINE_NUMBER
      , SAT_DATA.LINE_STATUS
      , SAT_DATA.QUANTITY
      , SAT_DATA.EXTENDED_PRICE
      , SAT_DATA.DISCOUNT
      , SAT_DATA.TAX
      , SAT_DATA.RETURN_FLAG            
      , SAT_DATA.DT_LOAD
      , SAT_DATA.HASH_DIFF
      , SAT_DATA.RECORD_SOURCE
FROM SAT_DATA SAT_DATA
LEFT JOIN {{ this }} SAT
	ON SAT.LINK_ID_LINEITEM_OPS =  SAT_DATA.LINK_ID_LINEITEM_OPS
   AND SAT.HASH_DIFF = SAT_DATA.HASH_DIFF
WHERE SAT.LINK_ID_LINEITEM_OPS IS NULL

