{{ config(
      alias='SATL_LINEITEM_OPS_DATES'
    , materialized='incremental')
}}


WITH SAT_DATA AS (
SELECT  
        MD5(L_ORDERKEY||L_PARTKEY||L_SUPPKEY) LINK_ID_LINEITEM_OPS
      , '{{ var('cod_tenant') }}' AS TENANT      
      , L_SHIPDATE AS SHIP_DATE
      , L_COMMITDATE AS COMMIT_DATE
      , L_RECEIPTDATE AS RECEIPT_DATE
      , L_SHIPINSTRUCT AS SHIP_INSTRUCTIONS
      , L_SHIPMODE AS SHIP_MODE
      , L_COMMENT AS COMMENT
      , CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS DT_LOAD            
      , MD5( COALESCE(L_SHIPDATE,'-1')
            ||COALESCE(L_COMMITDATE,'-1') 
            ||COALESCE(L_RECEIPTDATE,'-1') 
            ||COALESCE(L_SHIPINSTRUCT,'#') 
            ||COALESCE(L_SHIPMODE,'#') 
            ||COALESCE(L_COMMENT,'#') 
            ) HASH_DIFF
      , '{{ source('SF_SAMPLE', 'LINEITEM') }}' AS RECORD_SOURCE
FROM {{ source('SF_SAMPLE', 'LINEITEM') }} 
)

SELECT 
      SAT_DATA.LINK_ID_LINEITEM_OPS
      , SAT_DATA.TENANT
      , SAT_DATA.SHIP_DATE
      , SAT_DATA.COMMIT_DATE
      , SAT_DATA.RECEIPT_DATE
      , SAT_DATA.SHIP_INSTRUCTIONS
      , SAT_DATA.SHIP_MODE
      , SAT_DATA.COMMENT
      , SAT_DATA.DT_LOAD
      , SAT_DATA.HASH_DIFF
      , SAT_DATA.RECORD_SOURCE
FROM SAT_DATA SAT_DATA
LEFT JOIN {{ this }} SAT
	ON SAT.LINK_ID_LINEITEM_OPS =  SAT_DATA.LINK_ID_LINEITEM_OPS
   AND SAT.HASH_DIFF = SAT_DATA.HASH_DIFF
WHERE SAT.LINK_ID_LINEITEM_OPS IS NULL

