{{ config(
    alias='PIT_HIST_ORDERS'
  , materialized='table')
}}


SELECT 
      HUB.HUB_ID_ORDERS
    , HUB.DT_LOAD
    , SAT_DETAIL.DT_LOAD AS SAT_DETAIL_DT_LOAD
    , SAT_MAIN.DT_LOAD AS SAT_MAIN_DT_LOAD
    , HUB.TENANT
FROM {{ ref ('HUB_ORDERS' ) }} HUB
LEFT JOIN {{ ref ('SAT_ORDERS_DETAIL' ) }}  SAT_DETAIL ON HUB.HUB_ID_ORDERS = SAT_DETAIL.HUB_ID_ORDERS
LEFT JOIN {{ ref ('SAT_ORDERS_MAIN' ) }}  SAT_MAIN ON HUB.HUB_ID_ORDERS = SAT_MAIN.HUB_ID_ORDERS
