{{ config(
    alias='PIT_LAST_SUPPLIER'
  , materialized='view')
}}


SELECT 
      HUB.HUB_ID_SUPPLIER
    , HUB.DT_LOAD
    , SAT_STATIC.DT_LOAD AS SAT_STATIC_DT_LOAD
    , SAT_DETAIL.DT_LOAD AS SAT_DETAIL_DT_LOAD
    , HUB.TENANT
FROM {{ ref ('HUB_SUPPLIER' ) }} HUB
LEFT JOIN ( SELECT HUB_ID_SUPPLIER, DT_LOAD 
            FROM {{ ref ('SAT_SUPPLIER_STATIC' ) }} 
            QUALIFY ROW_NUMBER() OVER (PARTITION BY HUB_ID_SUPPLIER ORDER BY DT_LOAD DESC) = 1
            ) SAT_STATIC ON HUB.HUB_ID_SUPPLIER = SAT_STATIC.HUB_ID_SUPPLIER
LEFT JOIN ( SELECT HUB_ID_SUPPLIER, DT_LOAD 
            FROM {{ ref ('SAT_SUPPLIER_DETAIL' ) }} 
            QUALIFY ROW_NUMBER() OVER (PARTITION BY HUB_ID_SUPPLIER ORDER BY DT_LOAD DESC) = 1
            )  SAT_DETAIL ON HUB.HUB_ID_SUPPLIER = SAT_DETAIL.HUB_ID_SUPPLIER
