{{ config(
    alias='PIT_HIST_CUSTOMER'
  , materialized='table')
}}


SELECT 
      HUB.HUB_ID_CUSTOMER
    , HUB.DT_LOAD
    , SAT_CONTACT.DT_LOAD AS SAT_CONTACT_DT_LOAD
    , SAT_METRICS.DT_LOAD AS SAT_METRICS_DT_LOAD
    , HUB.TENANT
FROM {{ ref ('HUB_CUSTOMER' ) }} HUB
-- points to CUSTOMER_CONTACT v=1 (not latest)
LEFT JOIN {{ ref ('SAT_CUSTOMER_CONTACT', v=1 ) }}  SAT_CONTACT ON HUB.HUB_ID_CUSTOMER = SAT_CONTACT.HUB_ID_CUSTOMER
LEFT JOIN {{ ref ('SAT_CUSTOMER_METRICS' ) }}  SAT_METRICS ON HUB.HUB_ID_CUSTOMER = SAT_METRICS.HUB_ID_CUSTOMER
