{{ config(
    alias='PIT_HIST_PART'
  , materialized='table')
}}


SELECT 
      HUB.HUB_ID_PART
    , HUB.DT_LOAD
    , SAT_STATIC.DT_LOAD AS SAT_STATIC_DT_LOAD
    , SAT_MAIN.DT_LOAD AS SAT_MAIN_DT_LOAD
    , HUB.TENANT
FROM {{ ref ('HUB_PART' ) }} HUB
LEFT JOIN {{ ref ('SAT_PART_STATIC' ) }}  SAT_STATIC ON HUB.HUB_ID_PART = SAT_STATIC.HUB_ID_PART
LEFT JOIN {{ ref ('SAT_PART_MAIN' ) }}  SAT_MAIN ON HUB.HUB_ID_PART = SAT_MAIN.HUB_ID_PART
