{{ config(
    alias='PIT_HIST_SUPPLIER'
  , materialized='table')
}}


SELECT 
      HUB.HUB_ID_SUPPLIER
    , HUB.DT_LOAD
    , SAT_STATIC.DT_LOAD AS SAT_STATIC_DT_LOAD
    , SAT_DETAIL.DT_LOAD AS SAT_DETAIL_DT_LOAD
    , HUB.TENANT
FROM {{ ref ('HUB_SUPPLIER' ) }} HUB
LEFT JOIN {{ ref ('SAT_SUPPLIER_STATIC' ) }}  SAT_STATIC ON HUB.HUB_ID_SUPPLIER = SAT_STATIC.HUB_ID_SUPPLIER
LEFT JOIN {{ ref ('SAT_SUPPLIER_DETAIL' ) }}  SAT_DETAIL ON HUB.HUB_ID_SUPPLIER = SAT_DETAIL.HUB_ID_SUPPLIER
