{{ config(
    alias='PIT_LAST_ORDERS'
  , materialized='table')
}}


SELECT 
      HUB.HUB_ID_ORDERS
    , HUB.DT_LOAD
    , SAT_DETAIL.DT_LOAD AS SAT_DETAIL_DT_LOAD
    , SAT_MAIN.DT_LOAD AS SAT_MAIN_DT_LOAD
    , HUB.TENANT
FROM {{ ref ('HUB_ORDERS' ) }} HUB
LEFT JOIN ( SELECT HUB_ID_ORDERS, DT_LOAD 
            FROM {{ ref ('SAT_ORDERS_DETAIL' ) }} 
            QUALIFY ROW_NUMBER() OVER (PARTITION BY HUB_ID_ORDERS ORDER BY DT_LOAD DESC) = 1
            ) SAT_DETAIL ON HUB.HUB_ID_ORDERS = SAT_DETAIL.HUB_ID_ORDERS
LEFT JOIN ( SELECT HUB_ID_ORDERS, DT_LOAD 
            FROM {{ ref ('SAT_ORDERS_MAIN' ) }} 
            QUALIFY ROW_NUMBER() OVER (PARTITION BY HUB_ID_ORDERS ORDER BY DT_LOAD DESC) = 1
            )  SAT_MAIN ON HUB.HUB_ID_ORDERS = SAT_MAIN.HUB_ID_ORDERS
