{{ config(
    alias='PIT_LAST_PART'
  , materialized='view')
}}


SELECT 
      HUB.HUB_ID_PART
    , HUB.DT_LOAD
    , SAT_STATIC.DT_LOAD AS SAT_STATIC_DT_LOAD
    , SAT_MAIN.DT_LOAD AS SAT_MAIN_DT_LOAD
    , HUB.TENANT
FROM {{ ref ('HUB_PART' ) }} HUB
LEFT JOIN ( SELECT HUB_ID_PART, DT_LOAD 
            FROM {{ ref ('SAT_PART_STATIC' ) }} 
            QUALIFY ROW_NUMBER() OVER (PARTITION BY HUB_ID_PART ORDER BY DT_LOAD DESC) = 1
            ) SAT_STATIC ON HUB.HUB_ID_PART = SAT_STATIC.HUB_ID_PART
LEFT JOIN ( SELECT HUB_ID_PART, DT_LOAD 
            FROM {{ ref ('SAT_PART_MAIN' ) }} 
            QUALIFY ROW_NUMBER() OVER (PARTITION BY HUB_ID_PART ORDER BY DT_LOAD DESC) = 1
            )  SAT_MAIN ON HUB.HUB_ID_PART = SAT_MAIN.HUB_ID_PART
