{{ config(
    alias='PITL_LAST_OPS'
  , materialized='view')
}}


SELECT 
      LINK.LINK_ID_LINEITEM_OPS
    , LINK.DT_LOAD
    , SATL_DATES.DT_LOAD AS SATL_DATES_DT_LOAD
    , SATL_DETAIL.DT_LOAD AS SATL_DETAIL_DT_LOAD
    , LINK.TENANT
FROM {{ ref ('LNK_LINEITEM_ORDERS_PART_SUPPLIER' ) }} LINK
LEFT JOIN ( SELECT LINK_ID_LINEITEM_OPS, DT_LOAD 
            FROM {{ ref ('SATL_LINEITEM_OPS_DATES' ) }} 
            QUALIFY ROW_NUMBER() OVER (PARTITION BY LINK_ID_LINEITEM_OPS ORDER BY DT_LOAD DESC) = 1
            ) SATL_DATES ON LINK.LINK_ID_LINEITEM_OPS = SATL_DATES.LINK_ID_LINEITEM_OPS
LEFT JOIN ( SELECT LINK_ID_LINEITEM_OPS, DT_LOAD 
            FROM {{ ref ('SATL_LINEITEM_OPS_DETAIL' ) }} 
            QUALIFY ROW_NUMBER() OVER (PARTITION BY LINK_ID_LINEITEM_OPS ORDER BY DT_LOAD DESC) = 1
            )  SATL_DETAIL ON LINK.LINK_ID_LINEITEM_OPS = SATL_DETAIL.LINK_ID_LINEITEM_OPS
