{{ config(
    alias='PITL_HIST_OPS'
  , materialized='table')
}}


SELECT 
      LINK.LINK_ID_LINEITEM_OPS
    , LINK.DT_LOAD
    , SATL_DATES.DT_LOAD AS SATL_DATES_DT_LOAD
    , SATL_DETAIL.DT_LOAD AS SATL_DETAIL_DT_LOAD
    , LINK.TENANT
FROM {{ ref ('LNK_LINEITEM_ORDERS_PART_SUPPLIER' ) }} LINK
LEFT JOIN {{ ref ('SATL_LINEITEM_OPS_DATES' ) }}  SATL_DATES ON LINK.LINK_ID_LINEITEM_OPS = SATL_DATES.LINK_ID_LINEITEM_OPS
LEFT JOIN {{ ref ('SATL_LINEITEM_OPS_DETAIL' ) }}  SATL_DETAIL ON LINK.LINK_ID_LINEITEM_OPS = SATL_DETAIL.LINK_ID_LINEITEM_OPS
