{{ config(
    alias='HIST_CUSTOMER_BAL'
  , materialized='table')
}}


SELECT 
	PIT.HUB_ID_CUSTOMER 
	, HUB.CUSTOMER_KEY
	, CONTACT.CUSTOMER_NAME 
	, CONTACT.CUSTOMER_ADDRESS 
	, CONTACT.CUSTOMER_PHONE 
	, METRICS.ACCOUNT_BALANCE 
	, PIT.SAT_CONTACT_DT_LOAD
	, PIT.SAT_METRICS_DT_LOAD	
FROM {{ ref('PIT_HIST_CUSTOMER') }} PIT
LEFT JOIN {{ ref('HUB_CUSTOMER') }} HUB ON PIT.HUB_ID_CUSTOMER = HUB.HUB_ID_CUSTOMER
LEFT JOIN {{ ref('SAT_CUSTOMER_CONTACT', v=1) }} CONTACT ON PIT.HUB_ID_CUSTOMER = CONTACT.HUB_ID_CUSTOMER  AND PIT.SAT_CONTACT_DT_LOAD = CONTACT.DT_LOAD 
LEFT JOIN {{ ref('SAT_CUSTOMER_METRICS') }} METRICS ON PIT.HUB_ID_CUSTOMER = METRICS.HUB_ID_CUSTOMER  AND PIT.SAT_METRICS_DT_LOAD = METRICS.DT_LOAD 